const typePrefix = 'FRUITS:APP';

export const TYPES = {
    FETCH_FRUITS_LIST_SUCCESS: `${typePrefix}:FETCH_FRUITS_LIST_SUCCESS`,
    FETCH_FRUITS_LIST_FAILURE: `${typePrefix}:FETCH_FRUITS_LIST_FAILURE`,
    FETCH_FRUITS_LIST_REQUEST: `${typePrefix}:FETCH_FRUITS_LIST_REQUEST`,
};
